export type StatusFeature={label?:string;role?:string;state?:string;source?:string;lastUpdatedAt?:string|null;knownGap?:string;pagePath?:string;apiPath?:string}
export type StatusPayload={version?:string;platform?:string;source?:string;sourceMode?:string;state?:string;generatedAt?:string;authMode?:string;coverageMode?:string;targetSource?:string;collector?:Record<string,unknown>;freshness?:Record<string,unknown>;latestSnapshot?:Record<string,unknown>;coverage?:Record<string,unknown>;features?:StatusFeature[];storage?:{database?:string;binding?:string};limitations?:string[];notes?:string[];error?:{code?:string;message?:string}}
export const field=(source:Record<string,unknown>|undefined,key:string):unknown=>source?.[key]
export function plain(input:unknown):string{if(input==null||input==='')return '—';if(typeof input==='boolean')return input?'Yes':'No';if(typeof input==='number')return Number.isFinite(input)?input.toLocaleString('en-US'):'—';return String(input)}
export function label(input:unknown):string{return plain(input).replace(/_/g,' ').replace(/\b\w/g,char=>char.toUpperCase())}
export function absoluteTime(input:unknown):string{if(typeof input!=='string'||!input)return '—';const date=new Date(input);return Number.isNaN(date.getTime())?input:`${date.toISOString().slice(0,16).replace('T',' ')} UTC`}
export function relativeTime(input:unknown,now=Date.now()):string{if(typeof input!=='string'||!input)return '—';const ms=now-Date.parse(input);if(!Number.isFinite(ms))return absoluteTime(input);const minutes=Math.max(0,Math.floor(ms/60000));if(minutes<1)return 'just now';if(minutes<60)return `${minutes}m ago`;const hours=Math.floor(minutes/60);if(hours<48)return `${hours}h ago`;return `${Math.floor(hours/24)}d ago`}
export function tone(input:unknown):'good'|'warn'|'bad'|'flat'{const state=String(input??'').toLowerCase();if(['fresh','live'].includes(state))return 'good';if(['partial','stale','strong_stale','empty','demo'].includes(state))return 'warn';if(['failing','error','unconfigured'].includes(state))return 'bad';return 'flat'}
export function cadence(payload:StatusPayload):string{const seconds=field(payload.collector,'runCadenceSeconds');return typeof seconds==='number'&&seconds>0?(seconds>=60?`${Math.round(seconds/60)} minutes`:`${seconds} seconds`):'5 minutes'}
export function sanitizePayload(payload:StatusPayload):string{const safe={version:payload.version,platform:payload.platform,source:payload.source,sourceMode:payload.sourceMode,state:payload.state,generatedAt:payload.generatedAt,authMode:payload.authMode,coverageMode:payload.coverageMode,targetSource:payload.targetSource,storage:payload.storage,collector:payload.collector,freshness:payload.freshness,latestSnapshot:payload.latestSnapshot,coverage:payload.coverage,error:payload.error,notes:payload.notes};return JSON.stringify(safe,null,2).replace(/Bearer\s+[A-Za-z0-9._-]+/g,'Bearer [redacted]')}
export function escapeHtml(value:unknown):string{return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c))}
