name = "viewloom-collector-twitch"
main = "twitch.ts"
compatibility_date = "2026-05-18"

[vars]
INTRADAY_GENERATION_ENABLED = "true"

[triggers]
crons = ["*/5 * * * *"]

[[d1_databases]]
binding = "DB_TWITCH_HOT"
database_name = "vl_twitch_hot"
database_id = "b77221fe-80a3-4749-bc0e-d3ad54003dcf"
